name: MySQL Binlog Listener

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  monitor-webhooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Use Node.js 20.x

      - name: Decode SSL Certificate
        # Decodes the Base64 certificate stored as a secret into a .pem file
        run: |
          echo "${{ secrets.SSL_CERT_BASE64 }}" | base64 -d > DigiCertGlobalRootCA.crt.pem

      - name: Install Dependencies
        run: npm install

      - name: Run MySQL Binlog Listener
        run: node cronRunner.js
        env:
          ELASTICSEARCH_URL: ${{ secrets.ELASTICSEARCH_URL }}
          AZURE_SEARCH_ENDPOINT: ${{ secrets.AZURE_SEARCH_ENDPOINT }}
          AZURE_SEARCH_API_KEY: ${{ secrets.AZURE_SEARCH_API_KEY }}
